[package]
name = "rust-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# 난수 생성
rand = "0.8"
rand_chacha = "0.3"

# 해시 함수를 이용한 commit-reveal
sha2 = "0.10"
